"""initial schema

Revision ID: e9fa7ec2adfe
Revises:
Create Date: 2026-04-15 16:44:46.770338

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9fa7ec2adfe"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "donor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("institution", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("contact", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("donor", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_donor_name"), ["name"], unique=True)

    op.create_table(
        "genotype_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("genotype_status", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_genotype_status_code"), ["code"], unique=True)

    op.create_table(
        "org_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("org_unit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_org_unit_name"), ["name"], unique=True)

    op.create_table(
        "vial_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vial_status", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vial_status_code"), ["code"], unique=True)

    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("org_unit_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_unit_id"],
            ["org_unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "audit_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_event_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_event_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_event_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_event_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_event_entity_type"), ["entity_type"], unique=False
        )

    op.create_table(
        "genotype",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("chromosome_x", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("chromosome_2", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("chromosome_3", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("chromosome_4", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("chromosome_y", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phenotype", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("donor_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["donor_id"],
            ["donor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("genotype", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_genotype_name"), ["name"], unique=False)

    op.create_table(
        "genotype_status_link",
        sa.Column("genotype_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("set_at", sa.DateTime(), nullable=False),
        sa.Column("set_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["genotype_id"],
            ["genotype.id"],
        ),
        sa.ForeignKeyConstraint(
            ["set_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["genotype_status.id"],
        ),
        sa.PrimaryKeyConstraint("genotype_id", "status_id", "set_at"),
    )
    op.create_table(
        "vial",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("print_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("genotype_id", sa.Integer(), nullable=False),
        sa.Column("org_unit_id", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("flipped_from_id", sa.Integer(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("decommissioned_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["flipped_from_id"],
            ["vial.id"],
        ),
        sa.ForeignKeyConstraint(
            ["genotype_id"],
            ["genotype.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_unit_id"],
            ["org_unit.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vial", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vial_genotype_id"), ["genotype_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_vial_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_vial_print_code"), ["print_code"], unique=False)

    op.create_table(
        "vial_parentage",
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["vial.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["vial.id"],
        ),
        sa.PrimaryKeyConstraint("child_id", "parent_id", "role"),
    )
    op.create_table(
        "vial_status_link",
        sa.Column("vial_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("set_at", sa.DateTime(), nullable=False),
        sa.Column("set_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["set_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["vial_status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vial_id"],
            ["vial.id"],
        ),
        sa.PrimaryKeyConstraint("vial_id", "status_id", "set_at"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vial_status_link")
    op.drop_table("vial_parentage")
    with op.batch_alter_table("vial", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vial_print_code"))
        batch_op.drop_index(batch_op.f("ix_vial_is_active"))
        batch_op.drop_index(batch_op.f("ix_vial_genotype_id"))

    op.drop_table("vial")
    op.drop_table("genotype_status_link")
    with op.batch_alter_table("genotype", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_genotype_name"))

    op.drop_table("genotype")
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_event_entity_type"))
        batch_op.drop_index(batch_op.f("ix_audit_event_entity_id"))
        batch_op.drop_index(batch_op.f("ix_audit_event_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_event_actor_id"))
        batch_op.drop_index(batch_op.f("ix_audit_event_action"))

    op.drop_table("audit_event")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))

    op.drop_table("user")
    with op.batch_alter_table("vial_status", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vial_status_code"))

    op.drop_table("vial_status")
    with op.batch_alter_table("org_unit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_org_unit_name"))

    op.drop_table("org_unit")
    with op.batch_alter_table("genotype_status", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_genotype_status_code"))

    op.drop_table("genotype_status")
    with op.batch_alter_table("donor", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_donor_name"))

    op.drop_table("donor")
    # ### end Alembic commands ###
